apiVersion: v1
kind: Pod
metadata:
  name: predict-service
spec:
  containers:
  - name: predict
    image: kubeflow/training-job:v0.2
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: model
      mountPath: /trained_model
  volumes:
  - name: model
    persistentVolumeClaim:
      claimName: strategy-volume