apiVersion: v1
kind: Pod
metadata:
  name: model-selection
spec:
  containers:
  - name: model-selection
    image: kubeflow/distributed-training:v0.1
    command: ["python", "model_selection.py"]
    volumeMounts:
    - name: model
      mountPath: /trained_model
    resources:
      limits:
       cpu: 500m
  volumes:
  - name: model
    persistentVolumeClaim:
      claimName: strategy-volume