apiVersion: v1
kind: Pod
metadata:
  name: model-selection
spec:
  containers:
  - name: predict
    image: kubeflow/distributed-training:v0.1
    command: ["python"]
    args: ["/model_selection.py"]
    volumeMounts:
    - name: model
      mountPath: /trained_model
  restartPolicy: OnFailure
  volumes:
  - name: model
    persistentVolumeClaim:
      claimName: strategy-volume