# https://kserve.github.io/website/modelserving/v1beta1/tensorflow/
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fufu-sample
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
      # This is only needed on Mac M1
      image: "emacski/tensorflow-serving:2.6.0"
      # https://kserve.github.io/website/modelserving/storage/pvc/pvc/
      # Note that we are skipping `mountPath: /trained_model`
      storageUri: "pvc://strategy-volume/saved_model_versions"
  
      # Add the container arguments here
  containers:
  - args:
    - --model_name=fufu-sample
    - --port=9000
    - --rest_api_port=8080
    - --model_base_path=/trained_models/saved_model_versions
    - --rest_api_timeout_in_ms=60000
    