apiVersion: v1
kind: Pod
metadata:
  name: predict-service
spec:
  containers:
  - name: predict
    image: kubeflow/distributed-training:v0.1
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: model
      mountPath: /trained_model
    resources:
      limits:
        cpu: 500m
  volumes:
  - name: model
    persistentVolumeClaim:
      claimName: strategy-volume